// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NebrasProjectDomain.Models;

#nullable disable

namespace NebrasProjectDomain.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250830085620_SeedGovernorates")]
    partial class SeedGovernorates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NebrasProjectModels.Models.Citys.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolCount")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("NebrasProjectModels.Models.Governorates.Governorate", b =>
                {
                    b.Property<Guid>("GovernorateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CityCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovernorateImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolCount")
                        .HasColumnType("int");

                    b.HasKey("GovernorateId");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            GovernorateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CityCount = 11,
                            Description = "محافظة سورية تضم العاصمة دمشق وتعد مركز الإدارة الوطنية.",
                            GovernorateImage = "uploads/governorates/damascus.jpeg",
                            NameAr = "دمشق",
                            NameEn = "Damascus",
                            SchoolCount = 450
                        },
                        new
                        {
                            GovernorateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CityCount = 28,
                            Description = "محافظة تحيط بمدينة دمشق وتضم عدداً من المدن والبلدات.",
                            GovernorateImage = "uploads/governorates/rifdimashq.jpg",
                            NameAr = "ريف دمشق",
                            NameEn = "Rif Dimashq",
                            SchoolCount = 700
                        },
                        new
                        {
                            GovernorateId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CityCount = 44,
                            Description = "إحدى أكبر المحافظات السورية من حيث عدد السكان والمساحة.",
                            GovernorateImage = "uploads/governorates/aleppo.jpeg",
                            NameAr = "حلب",
                            NameEn = "Aleppo",
                            SchoolCount = 1000
                        },
                        new
                        {
                            GovernorateId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CityCount = 25,
                            Description = "محافظة تقع في وسط سوريا وتعد حلقة وصل بين الشمال والجنوب.",
                            GovernorateImage = "uploads/governorates/homs.jpg",
                            NameAr = "حمص",
                            NameEn = "Homs",
                            SchoolCount = 650
                        },
                        new
                        {
                            GovernorateId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CityCount = 22,
                            Description = "محافظة في وسط سوريا وتضم مدناً وبلدات متعددة.",
                            GovernorateImage = "uploads/governorates/hama.jpg",
                            NameAr = "حماة",
                            NameEn = "Hama",
                            SchoolCount = 450
                        },
                        new
                        {
                            GovernorateId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CityCount = 22,
                            Description = "محافظة ساحلية تقع على البحر المتوسط شمال غرب سوريا.",
                            GovernorateImage = "uploads/governorates/latakia.jpg",
                            NameAr = "اللاذقية",
                            NameEn = "Latakia",
                            SchoolCount = 400
                        },
                        new
                        {
                            GovernorateId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CityCount = 12,
                            Description = "محافظة ساحلية جنوب اللاذقية وتطل على البحر المتوسط.",
                            GovernorateImage = "uploads/governorates/tartus.jpg",
                            NameAr = "طرطوس",
                            NameEn = "Tartus",
                            SchoolCount = 250
                        },
                        new
                        {
                            GovernorateId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CityCount = 26,
                            Description = "محافظة تقع شمال غرب سوريا وتضم عدداً من المدن الرئيسية.",
                            GovernorateImage = "uploads/governorates/idlib.jpeg",
                            NameAr = "إدلب",
                            NameEn = "Idlib",
                            SchoolCount = 300
                        },
                        new
                        {
                            GovernorateId = new Guid("99999999-9999-9999-9999-999999999999"),
                            CityCount = 20,
                            Description = "محافظة جنوب سوريا وتشكل منفذاً حدودياً مع الأردن.",
                            GovernorateImage = "uploads/governorates/daraa.jpg",
                            NameAr = "درعا",
                            NameEn = "Daraa",
                            SchoolCount = 350
                        },
                        new
                        {
                            GovernorateId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CityCount = 14,
                            Description = "محافظة تقع جنوب سوريا وتضم العديد من القرى والبلدات.",
                            GovernorateImage = "uploads/governorates/suwayda.jpg",
                            NameAr = "السويداء",
                            NameEn = "As-Suwayda",
                            SchoolCount = 150
                        },
                        new
                        {
                            GovernorateId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CityCount = 14,
                            Description = "محافظة شرقية تقع على ضفاف نهر الفرات.",
                            GovernorateImage = "uploads/governorates/deirezor.jpg",
                            NameAr = "دير الزور",
                            NameEn = "Deir ez-Zor",
                            SchoolCount = 300
                        },
                        new
                        {
                            GovernorateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CityCount = 12,
                            Description = "محافظة شمال وسط سوريا تقع على نهر الفرات.",
                            GovernorateImage = "uploads/governorates/raqqa.jpg",
                            NameAr = "الرقة",
                            NameEn = "Raqqa",
                            SchoolCount = 200
                        },
                        new
                        {
                            GovernorateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CityCount = 23,
                            Description = "محافظة تقع شمال شرق سوريا وتضم مدناً رئيسية.",
                            GovernorateImage = "uploads/governorates/hasakah.jpg",
                            NameAr = "الحسكة",
                            NameEn = "Al-Hasakah",
                            SchoolCount = 350
                        },
                        new
                        {
                            GovernorateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CityCount = 5,
                            Description = "محافظة صغيرة تقع جنوب غرب سوريا قرب الجولان.",
                            GovernorateImage = "uploads/governorates/quneitra.jpg",
                            NameAr = "القنيطرة",
                            NameEn = "Quneitra",
                            SchoolCount = 80
                        });
                });

            modelBuilder.Entity("NebrasProjectModels.Models.Photos.SchoolPhoto", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCoverPhoto")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PhotoId");

                    b.HasIndex("SchoolId");

                    b.ToTable("SchoolPhotos");
                });

            modelBuilder.Entity("NebrasProjectModels.Models.Schools.School", b =>
                {
                    b.Property<Guid>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedRenovationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HeadTeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadTeacherNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequirementsMet")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Needs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SchoolId");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("NebrasProjectModels.Models.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NebrasProjectModels.Models.Citys.City", b =>
                {
                    b.HasOne("NebrasProjectModels.Models.Governorates.Governorate", "Governorate")
                        .WithMany("Cities")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("NebrasProjectModels.Models.Photos.SchoolPhoto", b =>
                {
                    b.HasOne("NebrasProjectModels.Models.Schools.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("NebrasProjectModels.Models.Schools.School", b =>
                {
                    b.HasOne("NebrasProjectModels.Models.Citys.City", null)
                        .WithMany("Schools")
                        .HasForeignKey("CityId");

                    b.HasOne("NebrasProjectModels.Models.Users.User", null)
                        .WithMany("AddedSchools")
                        .HasForeignKey("UserId");

                    b.HasOne("NebrasProjectModels.Models.Users.User", null)
                        .WithMany("ApprovedSchools")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("NebrasProjectModels.Models.Citys.City", b =>
                {
                    b.Navigation("Schools");
                });

            modelBuilder.Entity("NebrasProjectModels.Models.Governorates.Governorate", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("NebrasProjectModels.Models.Users.User", b =>
                {
                    b.Navigation("AddedSchools");

                    b.Navigation("ApprovedSchools");
                });
#pragma warning restore 612, 618
        }
    }
}
